### ISSUE TITLE
Photo grids (cards) similar to layouts/partials/bootstrap/icon-grid.html

### ISSUE THREAD

**Issue by pleasantone** [hugomods/bootstrap#100]
Would you have any objection to me taking a whack at creating "photo grid" (or extending icon-grid) to handle grids that have small photos in them?  I'm trying to make a clean and responsive version of something like:

https://www.goattrails.info/baja/people.html

Would you rather see it as an extension to icon grids (specifying a photo in the data file and no icon) or a separate partial?

**Comment by razonyang** [comment]
> Would you have any objection to me taking a whack at creating "photo grid" (or extending icon-grid) to handle grids that have small photos in them?

Sure, no problem! Any shortcode without _extra JS and CSS_ are welcome, since this all of this module's  shortcodes are created with Bootstrap built-in CSS (utilities), which allows users using it without extra JS and CSS.

> Would you rather see it as an extension to icon grids (specifying a photo in the data file and no icon) or a separate partial?

Another shortcode are prefered, it would be better for maintaining and understanding.
